Add initial files for zephyr interface
lsst-ts/ts_planning_tool pull request #1
Opened 2024-05-10 22:08 UTC by b1quint

2024-05-10 22:47 UTC, tribeiro requested changes
Please, move all the code to the regular package module, e.g., inside `python/lsst/planning/tool`.

I have the impression that the module names (prefixed with `test`) might create some confusion for pytest.

2024-05-20 20:55 UTC, tribeiro reviewed
Here is an initial round of comments.

2024-05-20 20:55 UTC, tribeiro commented on pyproject.toml
> +run_zephyr_interface = "lsst.ts.planning.tool.zephyr:run_zephyr_interface"
you need to update this now to 

```
run_zephyr_interface = "lsst.ts.planning.tool:run_zephyr_interface"
```

2024-05-20 20:55 UTC, tribeiro commented on python/lsst/ts/planning/tool/__init__.py
> -# This file is part of ts_planning_tool.
Please, restore all the deleted lines here, including the 


```
from .version import *  # Generated by sconsUtils
````

2024-05-20 20:55 UTC, tribeiro commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +"""
Please, move this docstring to the class docstring or to the `run_zephyr_interface` method. 

Also, please add the license header here:

```
# This file is part of ts_planning_tool.
#
# Developed for the LSST Data Management System.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

2024-05-20 20:55 UTC, tribeiro commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +        self.base_url = BASE_URL
2 things here.

If you are making the base_url static, from the `BASE_URL` variable, there's really no reason to store it as a class attribute. 

However, I think what we want to do here is be able to change this url, since we are planning to provide an intermediary service that will bridge with zephyr. I would suggest you do something like this:

```
    def __init__(self, username, api_token, base_url=BASE_URL, log=None):
        ...
        self.base_url = base_url
```

2024-05-20 20:55 UTC, tribeiro commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +        self.username = username
Is `username` being used anywhere? I see you setting it here and there but I don't think you use it as part of the interface. I suggest removing it.

2024-05-20 20:55 UTC, tribeiro commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +        self.api_token = api_token
I think you should also allow the user to provide no `api_token`, in which case, the methods should skip setting up the auth header. Again, this might be useful for the shim service we will provide.

You should probably make `api_token = None` the default.

2024-05-20 20:55 UTC, tribeiro commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +# Set up authentication
I don't think you should do this at the library level. The `ZephyrInterface` class provides a way for users to pass in the api token, so retrieving these values and passing them along should be at the application level.

2024-05-20 20:55 UTC, tribeiro commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +        self.log.setLevel(LOG_LEVEL)
I wouldn't do this here.

2024-05-20 20:55 UTC, tribeiro commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +LOG_LEVEL = logging.INFO
Please, don't do any log configuration on library level.

2024-05-20 20:55 UTC, tribeiro commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +    async def extract_test_case_from_test_execution(self, test_execution_json):
Is this method really necessary?

Note that it is not using any async operation neither it uses anything from the class (e.g. `self`). So, you might want to make it a regular method and also have it as a `staticmethod`.

2024-05-21 13:49 UTC, b1quint commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +    async def extract_test_case_from_test_execution(self, test_execution_json):
It might be useful for the user interface. But you are right, it can be a `staticmethod`

2024-05-21 13:51 UTC, b1quint commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +        self.log.setLevel(LOG_LEVEL)
Both lines or just the last one? If both, do you have another suggestion?

2024-05-30 15:35 UTC, tribeiro approved these changes
Looks good, but see my 2 inline comments before merging

2024-05-30 15:35 UTC, tribeiro commented on python/lsst/ts/planning/tool/__init__.py
> +# but WITHOUT ANY WsARRANTY; without even the implied warranty of
Typo introduced here

2024-05-30 15:35 UTC, tribeiro commented on tests/test_zephyr_interface.py
> +import unittest
Please, add the license header

2024-05-30 16:49 UTC, b1quint commented
Just for the record, I had many commits and the fixup was not properly working. So I cleared up the history line while keeping the same changes.

2024-05-30 16:50 UTC, merged