Tickets/dm 44631 - Add method to query test cycles
lsst-ts/ts_planning_tool pull request #2
Opened 2024-06-11 21:44 UTC by b1quint

2024-06-13 20:20 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +    async def get_user_name(self, json_object):
Maybe you can just use the `accountId` as function parameter. You are only accessing that parameter from the `json_object`.

2024-06-13 20:25 UTC, sebastian-aranda requested changes
Looks good! I've just left some minor comments :+1:.

2024-06-13 20:25 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +    async def get_user_name(self, json_object):
Maybe you can just use the `accountId` as function parameter. You are only accessing that parameter from the `json_object`.

2024-06-13 20:25 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +            "self" and "key" keys.
If you are keeping the `json_object` as param, here it should be:
```suggestion
            "self" and "accountId" keys.
```

2024-06-13 20:25 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +    async def get_project(self, json_object):
Same comment as before regarding using the value instead of the object.

2024-06-13 20:25 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +    async def get_status(self, json_object):
Same comment as before regarding using the value instead of the object.

2024-06-14 14:05 UTC, sebastian-aranda requested changes
Thanks for the great work here @b1quint ! I think we are good to go, I've left a couple doubts and requested some changes mainly for a couple docstrings that need to be updated :+1:.

2024-06-14 14:05 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +                    raise aiohttp.ClientError(
Is this related to getting `4xx` or `5xx` responses? I think you are already handling that with `aiohttp.ClientSession(raise_for_status=True)`.

2024-06-14 14:05 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +                    raise aiohttp.ClientError(
Maybe you can use `aiohttp.ClientSession(raise_for_status=True, auth=...)` as in other cases to handle the exceptions?

2024-06-14 14:05 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +            A dictionary containing the query parameters.
From the example below I see `cycle_keys` is being set as a `list` instead of a `dict`. Should this docstring be updated perhaps?

2024-06-14 14:05 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +        and "accountId" keys.
This docstring should be updated as now you are usign directly the `account_id` as param instead of the `json_object`.

2024-06-14 14:05 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +        "id" keys.
This docstring should be updated as now you are usign directly the `project_id` as param instead of the `json_object`.

2024-07-12 19:44 UTC, b1quint commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +                    raise aiohttp.ClientError(
Hmmm... So you are saying that I can simply remove it? Awesome, I will do!

2024-07-12 20:19 UTC, sebastian-aranda approved these changes
Thank you for your work on this @b1quint ! This looks good to me :+1:.

2024-07-12 20:38 UTC, merged