Create new methods to parse variables based on their IDs
lsst-ts/ts_planning_tool pull request #4
Opened 2024-08-16 19:18 UTC by b1quint

Zephyr Scale and Jira contain several variables in their database that are returned as JSON objects inside the GET requests' response. This makes it harder to tie the payload with the frontend quickly. This PR ensures that we have all the relevant variables parsed correctly in the API side. 

As part of the implementation of these methods to parse information, I will create a command line interface that we can use to easily confirm how the payload is set.

2024-09-30 17:26 UTC, sebastian-aranda requested changes
Nice work @b1quint. I took some time to try integrating the full refactor you did. I like how the code is designed. I've left some comments and requests, please take a look when convenient. After that I'll try jumping into adding a couple methods that I don't see now:
- Query all test cases for a given test cycle + their last executions. (to display the sidebar panel with the list of test cases).
- Query/Gather all test executions for a given test cycle **AND** test case.

2024-09-30 17:26 UTC, sebastian-aranda commented on README.md
> +Here are the list of environment variables required:
```suggestion
Here is the list of environment variables required:
```

2024-09-30 17:26 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +        Generic method to parse get requests to the Zephyr Scale API.
This is not really parsing, so perhaps this should be something like:
```suggestion
        Generic method to make HTTP GET requests to the Zephyr Scale API and return the payload.
```

2024-09-30 17:26 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/cli.py
> +        raise ValueError("ZEPHYR_TOKEN environment variable not set.")
```suggestion
        raise ValueError("ZEPHYR_API_TOKEN environment variable not set.")
```

2024-09-30 17:26 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/cli.py
> +        raise ValueError("JIRA_TOKEN environment variable not set.")
```suggestion
        raise ValueError("JIRA_API_TOKEN environment variable not set.")
```

2024-09-30 17:26 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/cli.py
> +        "--parse", choices=["raw", "full", "simple"], default="raw"
You missed the `-p` option here:
```suggestion
        "-p", "--parse", choices=["raw", "full", "simple"], default="raw"
```

2024-09-30 17:26 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
>      async def get_test_cycles(
Perhaps you could add a CLI method to query test cycles such as it happens with the `list_test_executions` method.

2024-09-30 17:26 UTC, sebastian-aranda commented on tests/test_zephyr_interface_no_ci.py
> +        payload_value_keys = ["inline", "testCase"]
You could also check the payload of the `inline` object, as the main purpose of the method is to bring the data of the test steps (which basically come inside the `inline` object).

2024-09-30 17:26 UTC, sebastian-aranda commented on tests/test_zephyr_interface_no_ci.py
The following test: `test_get_test_executions` is calling `zapi.get_test_executions`, but that method doesn't exist anymore.

2024-09-30 17:26 UTC, sebastian-aranda commented on tests/test_zephyr_interface_no_ci.py
On a separate note: we should try hooking unit tests to the CI, which doesn't seem to be running. We will probably need to hook up the library with `ts_jenkins_shared_library`. This can be probably done on a separate PR.

2024-09-30 17:26 UTC, sebastian-aranda commented on tests/test_zephyr_interface.py
The following test: `test_get_test_executions` is calling `zapi.get_test_executions`, but that method doesn't exist anymore.

2024-09-30 17:26 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
>          }
I would also add a couple other fields to parse: `component` and `folder`.

2024-09-30 17:26 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +        Get the a user name based on a json_obj payload containing `self` and
```suggestion
        Get the user name based on a json_obj payload containing `self` and
```

2024-09-30 17:26 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +            representing a user or  a single string containng the `accountId`.
```suggestion
            representing a user or a single string containng the `accountId`.
```

2024-10-04 17:58 UTC, b1quint commented on tests/test_zephyr_interface.py
This should be solved now

2024-10-08 13:18 UTC, sebastian-aranda approved these changes
Thanks for all the efforts put in here @b1quint ! PR approved :+1:.

2024-10-08 13:45 UTC, merged