DM-44804 Implement new function to collect the last Test Execution of a Test Case from Zephyr Scale
lsst-ts/ts_planning_tool pull request #5
Opened 2024-11-17 08:47 UTC by b1quint

2025-02-12 19:07 UTC, b1quint commented
We had a quick conversation. Here are a few items to change:
1. We want missing information in test execution steps grabbed from test case steps. 
2. We will treat "call to test" as normal executions whenever this is possible. It might be tricky when querying information from other tests. 

Use these two test executions as use cases: 
* BLOCK-E3851 / BLOCK-T308
* BLOCK-E4310 / BLOCK-T139

2025-02-25 14:21 UTC, sebastian-aranda commented
hey @b1quint , I have some general comments:
- New `complement` param suggests merging steps from case_steps and exec_steps, however it relates to "call to test" cases really, which is a different "use case". Also, I think this param is adding unnecessary complexity to the code: having to remember its purpose, remember to update all functions to include the complement param, creating confussions between the difference of `parse` vs `complement` (as they have similar purposes).
- In base to my previous comment I would suggest merging the logic of `complement` with `parse`. At the end, you just want to parse data that needs an extra query, so I think everything can be inside the `parse` scope.

I have some specific comments on the code, but I'll reference on the respective LOCs.

2025-02-25 14:43 UTC, sebastian-aranda requested changes

2025-02-25 14:43 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +        if complement and param_key == "testcases":
It seems the "call to test" logic is only for queries using a Test Case Key. I understand you are querying the same endpoint so that's why you kept Test Steps of Test Cases and Test Executions together, but I think it would be good to separate them in different methods such as: `get_steps_test_case` & `get_steps_test_execution`. That way you don't have to be using extra arguments to handle the logic and you just make "call to test" on the `get_steps_test_case` method.
Also all the logic from line 184 to 197 I would move that to a different function, something like `get_steps_call_to_test(json_steps: list)`

2025-02-25 14:43 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +            If True, the method will parse the payload. The default is True.
You defining a `parse` parameter in the docstrings, but you are not using it. I think this is a missing thing as statuses of steps are not being parsed yet. I.e. I'm still getting, e.g.:
```
"status": {
    "id": 6360083,
    "self": "https://api.zephyrscale.smartbear.com/v2/statuses/6360083",
},
```

2025-02-25 14:43 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +            #   same number of elements (steps).
You have some extra spaces in this comment.

2025-02-25 14:43 UTC, sebastian-aranda commented on python/lsst/ts/planning/tool/zephyr_interface.py
> +            )
I'm getting errors on this line. You are doing `test_execution["testCase"]["key"]`, but `test_execution["testCase"]` is not a dict and it already has the test case key.
```suggestion
            test_case_steps = await self.get_steps(
                test_execution["testCase"], complement=complement
            )
```

2025-02-25 14:43 UTC, sebastian-aranda commented on tests/test_zephyr_interface_no_ci.py
> +    # WARNING: This test will fail if you change the numner of steps in the
```suggestion
    # WARNING: This test will fail if you change the number of steps in the
```

2025-02-25 14:43 UTC, sebastian-aranda commented on tests/test_zephyr_interface_no_ci.py
> +        return json.load(file)
This looks like a potential candidate to move it to a `test_utils.py` file. I assume other tests will require this eventually.

2025-02-25 14:43 UTC, sebastian-aranda commented on tests/data/ideal_case_steps.json
I don't think we need to keep this in the repository. This represented an ideal case when we started designing this and it was mostly a requirement for the frontend, but payloads have taken a different format so I don't think this is relevant to be kept.

2025-02-25 14:43 UTC, sebastian-aranda commented on tests/data/ideal_case_steps_minimal.json
Similar to my previous comment, I don't think we need to keep this.

2025-03-07 22:35 UTC, b1quint commented on tests/test_zephyr_interface_no_ci.py
> +        return json.load(file)
I will leave this as it is for now. I always suffer with these imports in the testing.

2025-03-08 00:27 UTC, b1quint commented on tests/test_zephyr_interface_no_ci.py
> +        return json.load(file)
I ended up trying. And, yes. It was a pain. Especially because we use Unittest instead of Pytest. It is mainly because I am used to employ `fixtures`, which are natural from Pytest. I tried to make them work with Unittest and I failed. 

The import option is also problematic. Unless I make it part of the `ts_planning_tool` package.

2025-03-10 22:16 UTC, b1quint commented
Note to myself: I split the `get_steps` method into `get_steps_in_test_case` and `get_steps_in_test_execution`. The unit tests are all passing. However, when I run `zapi get test_execution BLOCK-E192 --parse full` in the command line, I get an assert error in L473: 
```
    assert len(test_execution_steps["values"]) == len(test_case_steps["values"])
```
Need to fix and need to write a unit test for this.

2025-03-10 22:19 UTC, b1quint commented
> Note to myself: I split the `get_steps` method into `get_steps_in_test_case` and `get_steps_in_test_execution`. The unit tests are all passing. However, when I run `zapi get test_execution BLOCK-E192 --parse full` in the command line, I get an assert error in L473:
> 
> ```
>     assert len(test_execution_steps["values"]) == len(test_case_steps["values"])
> ```
> 
> Need to fix and need to write a unit test for this.

Alright. I got it. This error occurs because `BLOCK-E192` is using an old version of the test case. Try this with `BLOCK-E306` and you will see that it works.

2026-06-03 21:49 UTC, b1quint commented
This PR became too long. I asked GitHub Copilot and Claude to split this work into three new PRs. Those are now in PR #8 , #9 and #10. They should be reviewed and merged in that order. I will close this PR for now.

2026-06-03 21:49 UTC, closed without merging

2026-06-03 21:49 UTC, b1quint commented
And I will keep the original branch for now until we merge all the other PRs.